-- 1.3.0.0版  优化语法


-- ------------------------------------索引-------------------------------------
DROP INDEX IDX_T_COURSE_PRICE ON T_COURSE_PRICE;
CREATE INDEX IDX_T_COURSE_PRICE_COURSEID
    ON T_COURSE_PRICE(COURSEID);
CREATE INDEX IDX_T_COURSE_PRICE_TIMEID
    ON T_COURSE_PRICE(COURSE_TIMEID);
CREATE INDEX IDX_T_COURSE_PRICE_CID_TID
    ON T_COURSE_PRICE(COURSEID, COURSE_TIMEID);
    
    
CREATE INDEX T_ORDER_USERID
    ON T_ORDER(USER_ID);

    
CREATE INDEX T_ORDER_DETAIL_ORDERID
    ON T_ORDER_DETAIL(ORDER_ID);
CREATE INDEX T_ORDER_DETAIL_ORDERID_TID
    ON T_ORDER_DETAIL(ORDER_ID,WARE_TIMEID);
    
    
CREATE INDEX T_ORDER_REPORT_USERID
    ON T_ORDER_REPORT(USER_ID);
CREATE INDEX T_ORDER_REPORT_TID
    ON T_ORDER_REPORT(COURSE_TIMEID);
CREATE INDEX T_ORDER_REPORT_PID
    ON T_ORDER_REPORT(COURSE_PRICEID);
CREATE INDEX T_ORDER_REPORT_UID_CID
    ON T_ORDER_REPORT(USER_ID,COURSEID);
    
    
CREATE INDEX T_ORDER_RETURN_USERID
    ON T_ORDER_RETURN(USERID);  
    
    
CREATE INDEX T_ORDER_ALIPAY_TRADENO
    ON T_ORDER_ALIPAY(TRADE_NO);     
    

CREATE INDEX T_ORDER_ALIPAY_LOG_TRADENO
    ON T_ORDER_ALIPAY_LOG(TRADE_NO); 
    
    
CREATE INDEX T_ORDER_CASHPAY_ORDERID
    ON T_ORDER_CASHPAY(ORDER_ID);     
    

CREATE INDEX T_ORDER_FUNDS_USERID
    ON T_ORDER_FUNDS(USERID);     
    
    
    