-- 1.3.3.0版 优化语法


-- T_INDEX_ADV表添加来源字段，ADV_SOURCE来源（0PC版，1手机版）
ALTER TABLE T_INDEX_ADV ADD COLUMN ADV_SOURCE TINYINT DEFAULT 0 NOT NULL AFTER COMPETE_ID;

-- 活动表添加报名时间
ALTER TABLE T_COMPETE ADD COLUMN VOTE_BEGINTIME DATETIME AFTER ATTEND_ENDTIME;
ALTER TABLE T_COMPETE ADD COLUMN VOTE_ENDTIME DATETIME AFTER VOTE_BEGINTIME;

-- 活动报名表添加视频播放次数
ALTER TABLE T_COMPETE_ATTEND ADD COLUMN PLAY_NUM INTEGER DEFAULT 0 AFTER VOTE_NUM;



-- 调整语法（手机版、PC版轮播图片分离）
INSERT INTO t_index_adv ( id, TITLE, FIELD_TYPE, ADV_SOURCE, CONTENT_TYPE, LINK_URL, IS_SHOW, PICTURE_FILE, DISPLAY_ORDER, CREATE_DATE, REMARK ) SELECT ( SELECT fun_next_seq ('T_INDEX_ADV')), TITLE, FIELD_TYPE, 1, CONTENT_TYPE, LINK_URL, IS_SHOW, LOCAL_FILE, DISPLAY_ORDER, CREATE_DATE, REMARK FROM t_index_adv adv WHERE adv.FIELD_TYPE = 0 AND adv.LOCAL_FILE != '';
UPDATE t_index_adv set LOCAL_FILE ='' WHERE FIELD_TYPE = 0 AND LOCAL_FILE != '';
commit;


