-- 1.3.4.0
-- 黄龙奖投票数据清空
UPDATE T_COMPETE_ATTEND_HLJ SET VOTE_NUM=0;
DELETE FROM T_COMPETE_VOTE WHERE COMPETE_ID IN (SELECT COMPETE_ID FROM T_COMPETE_ATTEND_HLJ);
commit;


-- 1.4.0.0 优化语法

-- ------------------------------------执行1 ddl -------------------------------------
-- 优化字段类型
ALTER TABLE T_USER_TEACHER modify APPLY_DATE DATETIME;
ALTER TABLE T_USER_TEACHER modify AUDIT_DATE DATETIME;

ALTER TABLE T_USER_UNION_MEMBER modify APPLY_DATE DATETIME;
ALTER TABLE T_USER_UNION_MEMBER modify AUDIT_DATE DATETIME;
ALTER TABLE T_USER_UNION_MEMBER ADD COLUMN REFERRER VARCHAR(75) AFTER ADDRESS;

ALTER TABLE T_COURSE modify APPLY_DATE DATETIME;
ALTER TABLE T_COURSE modify AUDIT_DATE DATETIME;

ALTER TABLE T_COURSE_VIDEO modify VIDEO_DURATION FLOAT(12,2);



-- T_USER_UNION_MEMBER字段维护
ALTER TABLE T_USER_UNION_MEMBER modify AGENCY_MODE VARCHAR(20);

