-- 1.4.0.0 优化语法（2016-05-30更新外网）

-- ------------------------------------执行1 ddl -------------------------------------
-- T_USER_TEACHER字段维护
ALTER TABLE T_USER_TEACHER ADD COLUMN PHONE VARCHAR(15) AFTER ADDRESS;
ALTER TABLE T_USER_TEACHER ADD COLUMN TEACHING VARCHAR(4000) AFTER HAND_IDCARD_FILE;
ALTER TABLE T_USER_TEACHER ADD COLUMN AWARDS VARCHAR(4000) AFTER TEACHING;


-- T_USER_UNION_MEMBER字段维护
ALTER TABLE T_USER_UNION_MEMBER modify AGENCY_MODE VARCHAR(20);




