-- 音乐大师网  普通索引
CREATE INDEX IDX_T_USER
    ON T_USER(USER_TYPE);
CREATE INDEX IDX_T_USER_NAME_PWD
    ON T_USER(USERNAME, PASSWORD);
CREATE UNIQUE INDEX IDX_T_USER_UNIQUE_USERNAME
    ON T_USER(USERNAME);
    
    
CREATE INDEX IDX_T_USER_TEACHER
    ON T_USER_TEACHER(TEACH_TYPE);
    
CREATE INDEX IDX_T_USER_BIND_PB
    ON T_USER_BIND(PLAT_TYPE,BIND_ID);
CREATE UNIQUE INDEX IDX_T_USER_BIND_BINDID_USERID
    ON T_USER_BIND(BIND_ID, USER_ID);
    
    
CREATE INDEX IDX_T_AGENCY
    ON T_AGENCY(AGENCY_TYPE);   
    

CREATE INDEX IDX_T_COURSE
    ON T_COURSE(CONTENT_TYPE, COURSE_TYPE);    
    

CREATE INDEX IDX_T_COURSE_TIME
    ON T_COURSE_TIME(COURSEID);    
    
    
CREATE INDEX IDX_T_COURSE_PRICE_COURSEID
    ON T_COURSE_PRICE(COURSEID);
CREATE INDEX IDX_T_COURSE_PRICE_TIMEID
    ON T_COURSE_PRICE(COURSE_TIMEID);
CREATE INDEX IDX_T_COURSE_PRICE_CID_TID
    ON T_COURSE_PRICE(COURSEID, COURSE_TIMEID);
    
    
CREATE INDEX T_ORDER_USERID
    ON T_ORDER(USER_ID);

    
CREATE INDEX T_ORDER_DETAIL_ORDERID
    ON T_ORDER_DETAIL(ORDER_ID);
CREATE INDEX T_ORDER_DETAIL_ORDERID_TID
    ON T_ORDER_DETAIL(ORDER_ID,WARE_TIMEID);
    
    
CREATE INDEX T_ORDER_REPORT_USERID
    ON T_ORDER_REPORT(USER_ID);
CREATE INDEX T_ORDER_REPORT_TID
    ON T_ORDER_REPORT(COURSE_TIMEID);
CREATE INDEX T_ORDER_REPORT_PID
    ON T_ORDER_REPORT(COURSE_PRICEID);
CREATE INDEX T_ORDER_REPORT_UID_CID
    ON T_ORDER_REPORT(USER_ID,COURSEID);
    
    
CREATE INDEX T_ORDER_RETURN_USERID
    ON T_ORDER_RETURN(USERID);  
    
    
CREATE INDEX T_ORDER_ALIPAY_TRADENO
    ON T_ORDER_ALIPAY(TRADE_NO);     
    

CREATE INDEX T_ORDER_ALIPAY_LOG_TRADENO
    ON T_ORDER_ALIPAY_LOG(TRADE_NO); 
    
    
CREATE INDEX T_ORDER_CASHPAY_ORDERID
    ON T_ORDER_CASHPAY(ORDER_ID);     
    

CREATE INDEX T_ORDER_FUNDS_USERID
    ON T_ORDER_FUNDS(USERID);     
    

CREATE INDEX IDX_T_ORDER_ANNUL_ORDERID
    ON T_ORDER_ANNUL (ORDER_ID);
-- 创建订单验证码唯一索引
CREATE UNIQUE INDEX IDX_T_ORDER_VERIFYCODE_UN
    ON T_ORDER_VERIFYCODE (COURSE_ID, COURSE_TIMEID, VERIFY_CODE);
CREATE INDEX IDX_T_ORDER_WECHATPAY_TRADENO
    ON T_ORDER_WECHATPAY(TRADE_NO);
    
    
CREATE INDEX IDX_T_COUPON_COUPONCODE 
    ON T_COUPON(COUPON_CODE);

CREATE INDEX IDX_T_COUPON_COURSE_COUPONID
    ON T_COUPON_COURSE(COUPON_ID);
CREATE INDEX IDX_T_COUPON_COURSE_COURSEID
    ON T_COUPON_COURSE(COURSE_ID);  
    
   
CREATE INDEX IDX_T_COMPETE_ATTEND_COMPETEID
    ON T_COMPETE_ATTEND(COMPETE_ID);
CREATE INDEX IDX_T_COMPETE_ATTEND_SONG_COMPETEID
    ON T_COMPETE_ATTEND_SONG(COMPETE_ID);
CREATE INDEX IDX_T_COMPETE_ATTEND_SONG_ATTENDID
    ON T_COMPETE_ATTEND_SONG(ATTEND_ID);    
CREATE INDEX IDX_T_COMPETE_COMMITTEE_COMPETEID
    ON T_COMPETE_COMMITTEE(COMPETE_ID); 
       
    
CREATE INDEX IDX_T_WXB_LOG
    ON T_WXB_LOG(COURSEID, SEQ);
CREATE INDEX IDX_T_WXB_LOG_USERID
    ON T_WXB_LOG(USERID);    
CREATE INDEX IDX_T_WXB_LOG_LOGINFLAG
    ON T_WXB_LOG(LOGINFLAG);     
CREATE INDEX IDX_T_WXB_LOG_LOGINTIME
    ON T_WXB_LOG(LOGINTIME);
    

CREATE INDEX IDX_T_HELP_THEME
    ON T_HELP_THEME(CATALOG_ID);
    

CREATE INDEX IDX_T_PICTURE
    ON T_PICTURE(OBJECT_ID);
    
    
CREATE INDEX IDX_T_SYSTEM_USER
    ON T_SYSTEM_USER(USERNAME,PASSWORD);
        

CREATE INDEX IDX_T_SYSTEM_USER_ROLE_USERID
    ON T_SYSTEM_USER_ROLE(USERID);      
CREATE INDEX IDX_T_SYSTEM_USER_ROLE_ROLEID
    ON T_SYSTEM_USER_ROLE(ROLEID);
    

CREATE INDEX IDX_T_SYSTEM_ROLE_MODULE_ROLEID
    ON T_SYSTEM_ROLE_MODULE(ROLEID);


CREATE INDEX IDX_T_SYSTEM_LOG
    ON T_SYSTEM_LOG(USERID);

    
CREATE INDEX IDX_T_SYSTEM_REGION_REGIONCODE
    ON T_SYSTEM_REGION(REGIONCODE);
CREATE INDEX IDX_T_SYSTEM_REGION_FULLCODE
    ON T_SYSTEM_REGION(FULLCODE);     

-- 2016.05.19+
CREATE UNIQUE INDEX IDX_T_USER_UNION_MEMBER_USERID_UNIONTYPE
    ON T_USER_UNION_MEMBER(USERID, UNION_TYPE);
CREATE INDEX IDX_T_USER_UNION_MEMBER_USERID
    ON T_USER_UNION_MEMBER(USERID);    
CREATE INDEX IDX_T_COURSE_VIDEO_COURSEID
    ON T_COURSE_VIDEO(COURSEID);    
CREATE INDEX IDX_T_COURSE_VIDEO_COURSE_TIMEID
    ON T_COURSE_VIDEO(COURSE_TIMEID);
    
    
    
    
    
    
    